services:
  sample.api:
    environment:
      - Keycloak__Authority=http://keycloak:8080/realms/company
      - Keycloak__Audience=portal-api
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ValidIssuers=http://localhost:8080/realms/company;http://keycloak:8080/realms/company
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=
      - OTEL_SERVICE_NAME=sample-api
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development
      - Cors__AllowedOrigins=http://localhost:5173;http://localhost:5174;http://localhost:4173;http://localhost:3000
    depends_on:
      - alloy
    ports:
      - "5157:8080"
    volumes:
      - ~/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ~/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ~/ASP.NET/Https:/root/.aspnet/https:ro

  backoffice:
    image: ${DOCKER_REGISTRY-}backoffice
    container_name: backoffice
    build:
      context: ../backoffice
      dockerfile: Dockerfile
      args:
        - VITE_OIDC_AUTHORITY=http://localhost:8080/realms/company
        - VITE_OIDC_REDIRECT_URI=http://localhost:5173/
        - VITE_API_BASE_URL=http://localhost:5157
    ports:
      - "5173:80"
    depends_on:
      - keycloak
      - sample.api
